# config to specify which modules will be used to render api docs from ml-agents package
folder: docs
modules:
    - name: mlagents
      file_name: Python-On-Off-Policy-Trainer-Documentation.md
      submodules:
          - trainers.trainer.on_policy_trainer
          - trainers.trainer.off_policy_trainer
          - trainers.trainer.rl_trainer
          - trainers.trainer.trainer
          - trainers.settings
    - name: mlagents
      file_name: Python-Optimizer-Documentation.md
      submodules:
        - trainers.optimizer.torch_optimizer
        - trainers.optimizer.optimizer
